services:
  app:
    build: ./
    volumes:
      - ./app:/var/www/app
  nginx:
    image: nginx 
    ports:
      - 8083:80 
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
